"""Run a shell through a PTY while streaming its terminal activity to Memo."""

from __future__ import annotations

import base64
import errno
import fcntl
import os
import pty
import select
import signal
import termios
import time
import tty
from contextlib import suppress
from pathlib import Path
from types import FrameType

from ..agents.shim import ensure_shims
from ..daemon.client import attach
from ..daemon.protocol import ProtocolError, request
from .filesystem import atomic_write
from .paths import StoragePaths

_BASH_RC = b"""# Generated by Memo. Changes will be overwritten.
if [ -r "${HOME}/.bashrc" ]; then
    . "${HOME}/.bashrc"
fi
if [ -n "${MEMO_SHIM_DIR:-}" ]; then
    PATH="${MEMO_SHIM_DIR}:${PATH}"
    export PATH
fi
"""

#: Terminal activity is reported synchronously, so this bounds how long a busy
#: daemon may stall the terminal. It is deliberately far above the protocol
#: default: a step publication or archive upload can hold the daemon for many
#: seconds, and that must not be mistaken for a dead daemon.
EVENT_TIMEOUT_SECONDS = 60.0

#: How often an idle terminal reports liveness. The daemon only needs this to
#: keep the attachment fresh and to notice ``memo end`` from another terminal.
HEARTBEAT_INTERVAL_SECONDS = 1.0


def _shell_argv(executable: str, paths: StoragePaths) -> list[str]:
    """Return shell arguments that preserve Memo interception after startup files."""
    if Path(executable).name != "bash":
        return [executable]
    rcfile = paths.runtime / "shell-init" / "bashrc"
    atomic_write(rcfile, _BASH_RC)
    return [executable, "--rcfile", str(rcfile)]


def _event(sequence: int, direction: str, data: bytes) -> dict[str, object]:
    return {
        "sequence": sequence,
        "direction": direction,
        "data": base64.b64encode(data).decode("ascii"),
    }


def _resize(source_fd: int, pty_fd: int) -> None:
    try:
        size = fcntl.ioctl(source_fd, termios.TIOCGWINSZ, b"\0" * 8)
        fcntl.ioctl(pty_fd, termios.TIOCSWINSZ, size)
    except OSError:
        pass


def run(
    path: Path,
    paths: StoragePaths | None = None,
    shell: str | None = None,
    stdin_fd: int = 0,
    stdout_fd: int = 1,
) -> int:
    paths = paths or StoragePaths.discover()
    shim_directory = ensure_shims(paths)
    allocation = attach(path, paths)
    while allocation.get("decision_required") or allocation.get("stale"):
        if allocation.get("stale"):
            os.write(
                stdout_fd,
                b"The recording changed while awaiting your choice; please choose again.\n",
            )
        prompt = (
            "A Memo recording already exists for this directory.\n\n"
            "1. Resume existing recording\n"
            "2. Start a new recording\n\n"
            "Choice [1]: "
        )
        choice = input(prompt).strip()
        decision = "replace" if choice == "2" else "resume"
        allocation = attach(
            path,
            paths,
            decision=decision,
            expected_session_id=str(allocation["session_id"]),
            expected_revision=int(allocation["revision"]),
        )
    terminal_id = allocation["terminal_id"]
    session_id = allocation["session_id"]
    executable = shell or os.environ.get("SHELL") or "/bin/sh"
    shell_argv = _shell_argv(executable, paths)
    pid, master_fd = pty.fork()
    if pid == 0:
        os.chdir(allocation["root"])
        environment = os.environ.copy()
        environment["MEMO_SESSION_ID"] = session_id
        environment["MEMO_TERMINAL_ID"] = terminal_id
        environment["MEMO_SHIM_DIR"] = str(shim_directory)
        environment["MEMO_RECORDING_ROOT"] = str(Path(allocation["root"]).resolve())
        environment["PATH"] = str(shim_directory) + os.pathsep + environment.get("PATH", "")
        os.execve(executable, shell_argv, environment)
    sequence = int(allocation["accepted_sequence"])
    original_mode = termios.tcgetattr(stdin_fd) if os.isatty(stdin_fd) else None
    previous_handlers: dict[int, object] = {}

    def forward(signum: int, _frame: FrameType | None) -> None:
        with suppress(ProcessLookupError):
            os.killpg(pid, signum)

    def resize(_signum: int, _frame: FrameType | None) -> None:
        _resize(stdin_fd, master_fd)

    try:
        if original_mode is not None:
            tty.setraw(stdin_fd, termios.TCSANOW)
        _resize(stdin_fd, master_fd)
        for signum in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP, signal.SIGQUIT):
            previous_handlers[signum] = signal.signal(signum, forward)
        previous_handlers[signal.SIGWINCH] = signal.signal(signal.SIGWINCH, resize)
        input_open = True
        ended = False
        recording = True
        last_heartbeat = 0.0

        def report(direction: str | None, data: bytes = b"") -> None:
            """Report terminal activity, giving up capture rather than the terminal.

            A recording failure must never take the shell down with it. Losing
            capture costs the tail of one recording; propagating the error would
            close the PTY master and kill the shell and any agent inside it.
            """
            nonlocal ended, recording, sequence
            if not recording:
                return
            events = [] if direction is None else [_event(sequence + 1, direction, data)]
            try:
                result = request(
                    str(paths.socket),
                    "events",
                    {
                        "session_id": session_id,
                        "terminal_id": terminal_id,
                        "events": events,
                    },
                    timeout=EVENT_TIMEOUT_SECONDS,
                )
            except (OSError, ProtocolError, TimeoutError, ValueError):
                recording = False
                with suppress(OSError):
                    os.write(
                        stdout_fd,
                        b"\r\nmemo: lost contact with the daemon; "
                        b"this terminal is no longer being recorded\r\n",
                    )
                return
            if result.get("recording_ended"):
                ended = True
                return
            accepted = result.get("accepted_sequence")
            if isinstance(accepted, int):
                sequence = accepted
            elif direction is not None:
                sequence += 1

        while True:
            readable, _, _ = select.select(
                [master_fd] + ([stdin_fd] if input_open else []), [], [], 0.1
            )
            if stdin_fd in readable:
                data = os.read(stdin_fd, 65536)
                if data:
                    # Forward before reporting so terminal latency never depends
                    # on how long the daemon takes to durably store the event.
                    os.write(master_fd, data)
                    report("input", data)
                    if ended:
                        break
                else:
                    input_open = False
            if master_fd in readable:
                try:
                    data = os.read(master_fd, 65536)
                except OSError as error:
                    if error.errno == errno.EIO:
                        break
                    raise
                if not data:
                    break
                os.write(stdout_fd, data)
                report("output", data)
                if ended:
                    break
            if not readable:
                now = time.monotonic()
                if now - last_heartbeat >= HEARTBEAT_INTERVAL_SECONDS:
                    last_heartbeat = now
                    report(None)
                    if ended:
                        break
        if ended:
            os.write(stdout_fd, b"\r\nmemo: recording ended\r\n")
            with suppress(ProcessLookupError):
                os.killpg(pid, signal.SIGHUP)
        _, status = os.waitpid(pid, 0)
        return os.waitstatus_to_exitcode(status)
    finally:
        try:
            request(str(paths.socket), "detach", {"terminal_id": terminal_id})
        except Exception:
            pass
        if original_mode is not None:
            termios.tcsetattr(stdin_fd, termios.TCSADRAIN, original_mode)
        for signum, handler in previous_handlers.items():
            signal.signal(signum, handler)
        os.close(master_fd)
